#! /usr/bin/env python3

import click
from pathlib import Path
from lib.cores import Database


@click.group()
def tbot():
    pass


@tbot.command
@click.argument("problems-file", type=click.Path(exists=True))
@click.option("-t", "--table-name", type=str, default="Problems")
def mkptb(problems_file, table_name):
    """
    Make problems table from a problems file.

    PROBLEMS-FILE: JSON format, first object must contain all properties in the following objects.
    """

    Path.mkdir(path := (Path.home() / ".lc-bp" / "problems"),
               exist_ok=True, parents=True)

    with Database(path / "problems.db") as db:
        db.create_table_from_file(table_name, problems_file)


commands = click.CommandCollection(sources=[tbot])

if __name__ == "__main__":
    commands()
